// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Color.proto

#ifndef PROTOBUF_Color_2eproto__INCLUDED
#define PROTOBUF_Color_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace AccountSearchPb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Color_2eproto();
void protobuf_AssignDesc_Color_2eproto();
void protobuf_ShutdownFile_Color_2eproto();

class Color;

// ===================================================================

class Color : public ::google::protobuf::Message {
 public:
  Color();
  virtual ~Color();

  Color(const Color& from);

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Color& default_instance();

  void Swap(Color* other);

  // implements Message ----------------------------------------------

  Color* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Color& from);
  void MergeFrom(const Color& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 uint32_r = 1 [default = 0];
  inline bool has_uint32_r() const;
  inline void clear_uint32_r();
  static const int kUint32RFieldNumber = 1;
  inline ::google::protobuf::uint32 uint32_r() const;
  inline void set_uint32_r(::google::protobuf::uint32 value);

  // optional uint32 uint32_g = 2 [default = 0];
  inline bool has_uint32_g() const;
  inline void clear_uint32_g();
  static const int kUint32GFieldNumber = 2;
  inline ::google::protobuf::uint32 uint32_g() const;
  inline void set_uint32_g(::google::protobuf::uint32 value);

  // optional uint32 uint32_b = 3 [default = 0];
  inline bool has_uint32_b() const;
  inline void clear_uint32_b();
  static const int kUint32BFieldNumber = 3;
  inline ::google::protobuf::uint32 uint32_b() const;
  inline void set_uint32_b(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AccountSearchPb.Color)
 private:
  inline void set_has_uint32_r();
  inline void clear_has_uint32_r();
  inline void set_has_uint32_g();
  inline void clear_has_uint32_g();
  inline void set_has_uint32_b();
  inline void clear_has_uint32_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uint32_r_;
  ::google::protobuf::uint32 uint32_g_;
  ::google::protobuf::uint32 uint32_b_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Color_2eproto();
  friend void protobuf_AssignDesc_Color_2eproto();
  friend void protobuf_ShutdownFile_Color_2eproto();

  void InitAsDefaultInstance();
  static Color* default_instance_;
};
// ===================================================================


// ===================================================================

// Color

// optional uint32 uint32_r = 1 [default = 0];
inline bool Color::has_uint32_r() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Color::set_has_uint32_r() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Color::clear_has_uint32_r() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Color::clear_uint32_r() {
  uint32_r_ = 0u;
  clear_has_uint32_r();
}
inline ::google::protobuf::uint32 Color::uint32_r() const {
  return uint32_r_;
}
inline void Color::set_uint32_r(::google::protobuf::uint32 value) {
  set_has_uint32_r();
  uint32_r_ = value;
}

// optional uint32 uint32_g = 2 [default = 0];
inline bool Color::has_uint32_g() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Color::set_has_uint32_g() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Color::clear_has_uint32_g() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Color::clear_uint32_g() {
  uint32_g_ = 0u;
  clear_has_uint32_g();
}
inline ::google::protobuf::uint32 Color::uint32_g() const {
  return uint32_g_;
}
inline void Color::set_uint32_g(::google::protobuf::uint32 value) {
  set_has_uint32_g();
  uint32_g_ = value;
}

// optional uint32 uint32_b = 3 [default = 0];
inline bool Color::has_uint32_b() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Color::set_has_uint32_b() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Color::clear_has_uint32_b() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Color::clear_uint32_b() {
  uint32_b_ = 0u;
  clear_has_uint32_b();
}
inline ::google::protobuf::uint32 Color::uint32_b() const {
  return uint32_b_;
}
inline void Color::set_uint32_b(::google::protobuf::uint32 value) {
  set_has_uint32_b();
  uint32_b_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace AccountSearchPb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Color_2eproto__INCLUDED
