//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CallArgus.proto
namespace TransmitParameters
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pack")]
  public partial class Pack : global::ProtoBuf.IExtensible
  {
    public Pack() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private byte[] _msg = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"unPack")]
  public partial class unPack : global::ProtoBuf.IExtensible
  {
    public unPack() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _seq = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seq
    {
      get { return _seq; }
      set { _seq = value; }
    }

    private bool _isTurnIp = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isTurnIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isTurnIp
    {
      get { return _isTurnIp; }
      set { _isTurnIp = value; }
    }

    private uint _serverip = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serverip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint serverip
    {
      get { return _serverip; }
      set { _serverip = value; }
    }

    private bool _is0836Suc = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"is0836Suc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is0836Suc
    {
      get { return _is0836Suc; }
      set { _is0836Suc = value; }
    }

    private bool _is0828Suc = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"is0828Suc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is0828Suc
    {
      get { return _is0828Suc; }
      set { _is0828Suc = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ToPackArgu")]
  public partial class ToPackArgu : global::ProtoBuf.IExtensible
  {
    public ToPackArgu() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _seq = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seq
    {
      get { return _seq; }
      set { _seq = value; }
    }

    private byte[] _msg = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackArgus")]
  public partial class PackArgus : global::ProtoBuf.IExtensible
  {
    public PackArgus() {}
    
    private bool _ispack;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ispack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ispack
    {
      get { return _ispack; }
      set { _ispack = value; }
    }

    private TransmitParameters.Pack _pack_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pack_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.Pack pack_data
    {
      get { return _pack_data; }
      set { _pack_data = value; }
    }

    private TransmitParameters.unPack _unpack_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unpack_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.unPack unpack_data
    {
      get { return _unpack_data; }
      set { _unpack_data = value; }
    }

    private TransmitParameters.ToPackArgu _toPackArgu = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"toPackArgu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.ToPackArgu toPackArgu
    {
      get { return _toPackArgu; }
      set { _toPackArgu = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetArgus")]
  public partial class NetArgus : global::ProtoBuf.IExtensible
  {
    public NetArgus() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _socket;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"socket", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint socket
    {
      get { return _socket; }
      set { _socket = value; }
    }

    private byte[] _notify_msg = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"notify_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] notify_msg
    {
      get { return _notify_msg; }
      set { _notify_msg = value; }
    }

    private byte[] _send_recv_data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"send_recv_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] send_recv_data
    {
      get { return _send_recv_data; }
      set { _send_recv_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    

    private string _notifyMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notifyMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notifyMsg
    {
      get { return _notifyMsg; }
      set { _notifyMsg = value; }
    }

    private byte[] _codedata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"codedata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] codedata
    {
      get { return _codedata; }
      set { _codedata = value; }
    }

    private string _codeurl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"codeurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string codeurl
    {
      get { return _codeurl; }
      set { _codeurl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CallArgus")]
  public partial class CallArgus : global::ProtoBuf.IExtensible
  {
    public CallArgus() {}
    
    private bool _isCallSucess;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isCallSucess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isCallSucess
    {
      get { return _isCallSucess; }
      set { _isCallSucess = value; }
    }

    private TransmitParameters.PackArgus _pack_argu = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pack_argu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.PackArgus pack_argu
    {
      get { return _pack_argu; }
      set { _pack_argu = value; }
    }

    private TransmitParameters.NetArgus _net_argu = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"net_argu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.NetArgus net_argu
    {
      get { return _net_argu; }
      set { _net_argu = value; }
    }

    private TransmitParameters.LoginResult _loginresult = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginresult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransmitParameters.LoginResult loginresult
    {
      get { return _loginresult; }
      set { _loginresult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}